name: dask-images

on:
  push:
    tags:
      - "*"
jobs:
  htcondor-wn:
    runs-on: ubuntu-latest
    #env:
    #  DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build container base image
        uses: docker/build-push-action@v2
        with:
          context: ./htcondor/execute/dask/
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/htcondor-dask-wn:${{ env.RELEASE_VERSION }}
          file: ./htcondor/execute/dask/Dockerfile
          platforms: linux/amd64

  jupyterlab-dask-base-image:
    runs-on: ubuntu-latest
    #env:
    #  DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build container base image
        uses: docker/build-push-action@v2
        with:
          context: ./jupyterlab/
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/jupyterlab:${{ env.RELEASE_VERSION }}-base
          file: ./jupyterlab/Dockerfile.base
          platforms: linux/amd64

  jupyterlab-dask-image:
    needs: jupyterlab-dask-base-image
    runs-on: ubuntu-latest
    #env:
    #  DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build container base+DASK image
        uses: docker/build-push-action@v2
        with:
          context: ./jupyterlab/
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/jupyterlab:${{ env.RELEASE_VERSION }}-dask
          file: ./jupyterlab/Dockerfile.dask-cc7
          platforms: linux/amd64
          build-args: "NOTEBOOK_VERSION=${{ env.RELEASE_VERSION }}"

  jupyterlab-dask-test-image:
    needs: jupyterlab-dask-base-image
    runs-on: ubuntu-latest
    #env:
    #  DOCKER_TARGET_PLATFORM: linux/arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Repo Owner
        id: get_repo_owner
        run: echo ::set-output name=repo_owner::$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
      - name: Build container base+DASK image
        uses: docker/build-push-action@v2
        with:
          context: ./jupyterlab/
          outputs: "type=registry,push=true"
          tags: |
            ghcr.io/${{ steps.get_repo_owner.outputs.repo_owner }}/jupyterlab:${{ env.RELEASE_VERSION }}-dask-test
          file: ./jupyterlab/Dockerfile.dask-cc7-test
          platforms: linux/amd64
          build-args: "NOTEBOOK_VERSION=${{ env.RELEASE_VERSION }}"